from __future__ import annotations
from typing import Any, List, Optional, Set, Tuple, Union

try:
    from ..Data.TypeMgr import PlantType
except ImportError:
    try:
        from PvzRH_node.Data.TypeMgr import PlantType
    except ImportError:
        PlantType = None

# Import static dictionaries generated by build_recipes.py
try:
    from .recipe_data import INGREDIENT_TO_RESULTS, PAIR_TO_RESULT, RESULT_TO_PARENTS
except ImportError:
    from .recipe_data import (
        INGREDIENT_TO_RESULTS,
        PAIR_TO_RESULT,
        RESULT_TO_PARENTS,
    )


def _to_id(val: Any) -> int:
    """Extracts raw integer ID handling Enums, Tuples, and int values."""
    # 1. Extract .value if Enum member
    if hasattr(val, "value"):
        val = val.value

    # 2. Extract first element if wrapped in a tuple/list (e.g. (0, 'Peashooter'))
    while isinstance(val, (tuple, list)):
        if not val:
            raise ValueError("Cannot extract ID from an empty tuple/list.")
        val = val[0]
        if hasattr(val, "value"):
            val = val.value

    return int(val)


def _to_type(plant_id: int) -> Union[Any, int]:
    if PlantType is not None:
        try:
            return PlantType(plant_id)
        except (ValueError, KeyError):
            pass
    return plant_id


class RecipeData:
    """Query interface for Plants vs. Zombies Fusion recipe trees."""

    # 1. Get all fusions that can be made from a PlantType
    @staticmethod
    def get_fusions_from(plant: Union[int, Any]) -> List[Union[Any, int]]:
        """Returns all resulting PlantTypes that can be crafted using this plant."""
        p_id = _to_id(plant)
        results = INGREDIENT_TO_RESULTS.get(p_id, set())
        return [_to_type(res_id) for res_id in sorted(results)]

    # 2. Get all sub-ingredients (recursive dependencies with cycle protection)
    @staticmethod
    def get_all_ingredients(plant: Union[int, Any]) -> List[Union[Any, int]]:
        """
        Recursively finds all sub-plants needed to craft this PlantType.
        """
        target_id = _to_id(plant)
        visited: Set[int] = set()

        def _traverse(current_id: int):
            for p1, p2 in RESULT_TO_PARENTS.get(current_id, []):
                for parent_id in (p1, p2):
                    if parent_id not in visited and parent_id != target_id:
                        visited.add(parent_id)
                        _traverse(parent_id)

        _traverse(target_id)
        return [_to_type(pid) for pid in sorted(visited)]

    # 3. Get fusion result from two child PlantTypes
    @staticmethod
    def get_fusion_result(
        plant1: Union[int, Any], plant2: Union[int, Any]
    ) -> Optional[Union[Any, int]]:
        """Returns the resulting PlantType when combining plant1 and plant2."""
        p1 = _to_id(plant1)
        p2 = _to_id(plant2)
        pair = tuple(sorted((p1, p2)))
        res_id = PAIR_TO_RESULT.get(pair) #type: ignore
        return _to_type(res_id) if res_id is not None else None

    # 4. Get direct parent recipe pairs for a target plant
    @staticmethod
    def get_direct_parents(
        plant: Union[int, Any]
    ) -> List[Tuple[Union[Any, int], Union[Any, int]]]:
        """Returns the immediate parent pairs that combine into this plant."""
        p_id = _to_id(plant)
        pairs = RESULT_TO_PARENTS.get(p_id, [])
        return [(_to_type(p1), _to_type(p2)) for p1, p2 in pairs]