[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PvzRH_node"
version = "3.8"
authors = [
    { name = "Tproplay" }
]
description = "A procedural, context-aware visual scripting layout framework for PvZ Fusion modding graphs."
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "typing_extensions>=4.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff.lint]
ignore = ["F541"]